<?php

use common\helpers\GroupDaysHelper;
use common\helpers\GroupHelper;
use common\models\Group;
use dmstr\bootstrap\Tabs;
use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var yii\web\View $this
 * @var common\models\Group $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('models', 'Group'). ': ' .$model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('models', 'Groups'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="group-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
                '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('ui', 'Edit'),
                [ 'update', 'id' => $model->id],
                ['class' => 'btn btn-info']) ?>

            <?= Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('ui', "New"),
                ['create'],
                ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
                . Yii::t('ui', "Full list"), ['index'], ['class'=>'btn btn-warning']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('common\models\Group'); ?>

    <?= DetailView::widget([
        'template' => "<tr><th style='width: 20%'>{label}</th><td>{value}</td></tr>",
        'model' => $model,
        'attributes' => [
            'name',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'subject_id',
                'value' => ($model->subject ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['subject/index']).' '.
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->subject->name, ['subject/view', 'id' => $model->subject->id,]).' '.
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Group'=>['subject_id' => $model->subject_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'teacher_id',
                'value' => ($model->teacher ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['teacher/index']).' '.
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->teacher->full_name, ['teacher/view', 'id' => $model->teacher->id,]).' '.
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Group'=>['teacher_id' => $model->teacher_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            'level',
            [
                'attribute' => 'action',
                'value' => function (Group $model) {
                    return GroupHelper::getActionLabel($model->action);
                },
                'format' => 'raw'
            ],
            [
                'attribute' => 'type',
                'value' => function (Group $model) {
                    return GroupHelper::getTypeName($model->type);
                },
                'format' => 'raw'
            ],
            [
                'attribute' => 'ActivePrice',
                'value' => function (Group $model) {
                    return nf($model->price);
                },
                'format' => 'raw'
            ],
            // 'price',
            'period_start',
            [
                'attribute' => 'duration',
                'value' => function (Group $model) {
                    return GroupHelper::getDurationName($model->duration);
                }
            ],
            'start_hour',
            'end_hour',
            [
                'attribute' => 'studyDays',
                'value' => function (Group $model) {
                    return $model->getDaysText();
                },
            ],
            [
                'attribute' => 'status',
                'value' => function (Group $model) {
                    return GroupHelper::getStatusLabel($model->status);
                },
                'format' => 'raw'
            ],
        ],
    ]); ?>

    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('ui', "Delete"), ['delete', 'id' => $model->id],
        [
            'class' => 'btn btn-danger',
            'data-confirm' => '' . 'Are you sure to delete this item?' . '',
            'data-method' => 'post',
        ]); ?>
    <?php $this->endBlock(); ?>

    <?= Tabs::widget(
        [
            'id' => 'relation-tabs',
            'encodeLabels' => false,
            'items' => [
                [
                    'label'   => '<b class=""><i class="fa fa-info-circle"></i> '.Yii::t('ui', 'More information').'</b>',
                    'content' => $this->blocks['common\models\Group'],
                    'active'  => true,
                ],
            ]
        ]);
    ?>
</div>
